version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5428:5428"

#version: '3.9'

#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: mysecretpassword
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    restart: unless-stopped
#
#volumes:
#  postgres_data: {}